# Generated by Django 3.0.5 on 2020-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0002_auto_20200510_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
