# Generated by Django 3.0.5 on 2020-05-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0004_auto_20200510_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('diagnosis_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('medication_code', models.IntegerField()),
                ('prescription_required', models.BooleanField()),
            ],
        ),
    ]
