# Generated by Django 3.0.5 on 2020-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0006_auto_20200513_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_package_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
