# Generated by Django 3.0.5 on 2020-05-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0008_remove_medication_medication_package_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='session',
            name='prescriptions',
        ),
    ]
