# Generated by Django 3.0.5 on 2020-05-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0009_auto_20200518_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_interface.Diagnosis'),
        ),
        migrations.AddField(
            model_name='session',
            name='prescriptions',
            field=models.ManyToManyField(to='doctor_interface.Medication'),
        ),
    ]
