# Generated by Django 3.0.5 on 2020-05-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0010_auto_20200518_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_test', models.TextField()),
                ('blood_test_code', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
