# Generated by Django 3.0.5 on 2020-06-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0020_auto_20200524_1600'),
        ('doctor_interface', '0011_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('blood_tests', models.ManyToManyField(to='doctor_interface.BloodTest')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.Patient')),
            ],
        ),
    ]
