# Generated by Django 3.0.5 on 2020-06-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0012_bloodtestrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='diagnosis',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='session',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='doctor_interface.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='session',
            name='prescriptions',
            field=models.ManyToManyField(related_name='prescriptions', to='doctor_interface.Medication'),
        ),
    ]
