# Generated by Django 3.0.5 on 2020-06-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0013_auto_20200601_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication',
            field=models.TextField(),
        ),
    ]
