# Generated by Django 3.0.5 on 2020-06-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0016_auto_20200603_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtestrequest',
            name='blood_tests',
        ),
        migrations.RemoveField(
            model_name='bloodtestrequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='bloodtestrequest',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BloodTest',
        ),
        migrations.DeleteModel(
            name='BloodTestRequest',
        ),
    ]
