# Generated by Django 3.0.5 on 2020-06-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0021_auto_20200531_2010'),
        ('doctor_interface', '0017_auto_20200617_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_test', models.TextField()),
                ('blood_test_code', models.IntegerField()),
                ('price', models.IntegerField()),
                ('group', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodTestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('blood_tests', models.ManyToManyField(to='doctor_interface.BloodTest')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.Patient')),
            ],
        ),
    ]
