# Generated by Django 3.0.5 on 2020-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_interface', '0018_bloodtest_bloodtestrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='prescriptions', to='doctor_interface.Medication'),
        ),
    ]
