# Generated by Django 3.0.5 on 2020-04-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_models', '0003_auto_20200421_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_session', models.DateTimeField(verbose_name='Time of Session')),
                ('free_text', models.CharField(blank=True, max_length=2000)),
                ('medications', models.CharField(blank=True, max_length=2000)),
                ('special_request', models.CharField(blank=True, max_length=2000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.Patient')),
            ],
        ),
    ]
