# Generated by Django 3.0.5 on 2020-04-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
