# Generated by Django 3.0.5 on 2020-05-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
