# Generated by Django 3.0.5 on 2020-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_desk', '0003_doctorslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='room',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
