# Generated by Django 3.0.5 on 2020-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_desk', '0004_auto_20200506_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
