# Generated by Django 3.0.5 on 2020-05-24 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_desk', '0004_auto_20200510_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
