# Generated by Django 3.0.5 on 2020-05-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_desk', '0005_auto_20200524_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 24)),
        ),
    ]
