# Generated by Django 3.0.5 on 2020-05-08 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception_desk', '0005_auto_20200506_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='room',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='start_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
