# Generated by Django 3.0.5 on 2020-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identifying_number',
            field=models.CharField(max_length=30),
        ),
    ]
