# Generated by Django 3.0.5 on 2020-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0003_auto_20200421_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
