# Generated by Django 3.0.5 on 2020-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0004_appointment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
