# Generated by Django 3.0.5 on 2020-04-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0005_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
    ]
