# Generated by Django 3.0.5 on 2020-04-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0007_trydoctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryDoctor',
        ),
    ]
