# Generated by Django 3.0.5 on 2020-04-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_doctor'),
        ('general_models', '0008_delete_trydoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
