# Generated by Django 3.0.5 on 2020-04-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0010_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
