# Generated by Django 3.0.5 on 2020-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0013_appointment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
