# Generated by Django 3.0.5 on 2020-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0014_appointment_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='identifying_number',
            new_name='clinic_identifying_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='patient',
            name='visa_number',
            field=models.CharField(default=12345, max_length=30),
            preserve_default=False,
        ),
    ]
