# Generated by Django 3.0.5 on 2020-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0016_auto_20200505_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
