# Generated by Django 3.0.5 on 2020-05-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0017_appointment_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
