# Generated by Django 3.0.5 on 2020-05-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0018_appointment_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
    ]
