# Generated by Django 3.0.5 on 2020-05-24 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0019_remove_appointment_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
    ]
