# Generated by Django 3.0.5 on 2020-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0020_auto_20200524_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='arrived',
            field=models.TimeField(default=None, null=True),
        ),
    ]
