# Generated by Django 3.0.5 on 2020-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0021_auto_20200531_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='done',
            field=models.TimeField(default=None, null=True),
        ),
    ]
